name: Treasure of China
favicon: null
layout_spectrum: 0.10659
typography_spectrum: 0.42025883332826197
title: Chinese Restaurant in Bromley
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312e27'
    - '#d4e5ec'
    - '#675837'
    - '#98a6a9'
    - '#b3703c'
  brandStrength: 0.25
  lightness: 0.9153023834805936
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
